apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-service
  name: payment-service
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: payment-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - image: registry.gitlab.com/loja-energetica/payment-service:arm-1.0.002-SNAPSHOT
          imagePullPolicy: Always
          name: payment-service
          ports:
            - containerPort: 8084
              name: http
              protocol: TCP
          env:
            - name: DATA_SOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: DATA_SOURCE_URL
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
