apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: le-frontend
  name: le-frontend
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: le-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: le-frontend
    spec:
      containers:
        - image: registry.gitlab.com/loja-energetica/loja-energetica-new-frontend:arm-node
          imagePullPolicy: Always
          name: le-frontend
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
