apiVersion: v1
  data:
    DATA_SOURCE_URL: jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/domain_service
  kind: ConfigMap
  metadata:
    name: domain-service-config
    namespace: default